export const SET_SHOW_DATA = 'SET_SHOW_DATA';
export const FETCH_SHOW_DATA = 'FETCH_SHOW_DATA';
export const SET_EPISODE_DATA = 'SET_EPISODE_DATA';
export const FETCH_EPISODE_DATA = 'FETCH_EPISODE_DATA';
export const SET_SHOW_EPISODES_DATA = 'SET_SHOW_EPISODES_DATA';
export const FETCH_SHOW_EPISODES_DATA = 'FETCH_SHOW_EPISODES_DATA';
